# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest


jobs:
- job: test
 
  pool:
    name: Default
  steps:
    - task: emailReportTask@1
      inputs:
        sendMailConditionConfig: 'Always'
        subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
        toAddress: 'swathi9796@gmail.com'
        defaultDomain: 'gmail.com'
        emailBodyFormat: 'InLine'
        emailBody: 'Build notify'
        groupTestResultsBy: 'run'
        includeCommits: true
        maxTestFailuresToShow: '15'
        includeOthersInTotal: false
        usePreviousEnvironment: false
        smtpConnectionEndpoint: 'SMTPconnectiontest'
      condition: always()

- job: Bar
  dependsOn: test
  condition: failed()
  variables:
    - name: one
      value : Success
 
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        curl -H 'Content-Type: application/json' -d ' {"text": $(one) }' $(webhookurl)
  