# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
        - bash: |
            curl -v -X POST https://accenture.webhook.office.com/webhookb2/c6aea564-fe88-48b4-9fa6-a737f1425035@e0793d39-0939-496d-b129-198edd916feb/IncomingWebhook/15e5aab7761341388f908a5fe592fbc9/570d319c-d336-48a2-b32e-88ba623aa565 \
              -H 'Content-Type: application/json; charset=utf-8' \
              --data-binary @- << EOF
              {
                "type":"message",
                "attachments":[
                  {
                    "contentType":"application/vnd.microsoft.card.adaptive",
                    "contentUrl":null,
                    "content":{
                      "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
                      "type":"AdaptiveCard",
                      "version":"1.2",
                      "body":[
                        {
                          "type": "TextBlock",
                          "text": "Hello"
                        }
                      ]
                    }
                  }
                ]
              }
            EOF      
      displayName: swathi
      echo 'Hello world'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: sendemail@0
  inputs:
    emailToAddress: 'swathi9796@gmail.com'
    emailCcAddress: 'swathi9796@gmail.com'
    emailSubject: 'Build  notification'
    emailBody: 'Build  notification'


- task: emailReportTask@1
  inputs:
    sendMailConditionConfig: 'Always'
    subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
    toAddress: 'swathi9796@gmail.com'
    defaultDomain: 'gmail.com'
    emailBodyFormat: 'InLine'
    emailBody: 'Build notify'
    groupTestResultsBy: 'run'
    includeCommits: true
    maxTestFailuresToShow: '15'
    includeOthersInTotal: false
    usePreviousEnvironment: false
    smtpConnectionEndpoint: 'SMTPconnectiontest'

